### ISSUE TITLE
Null check required in Tags.java:59

### ISSUE THREAD

**Issue by amsanjeev** [hanuor/onyx#2]
A null check is required before operating on the list of RecognitionResults in doInBackground() in Tags.java .  

Without that the following error will be thrown

_java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                               at com.hanuor.onyx.hub.Tags$1.doInBackground(Tags.java:59)
                                                                               at com.hanuor.onyx.hub.Tags$1.doInBackground(Tags.java:53)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                               at java.lang.Thread.run(Thread.java:761)_ 

File : [Tags.java](https://github.com/hanuor/onyx/blob/master/onyx/src/main/java/com/hanuor/onyx/hub/Tags.java) 
location : L59

**Comment by ghost** [comment]
Hi Amrit,
Thank you for reporting the issue. We've resolved this and updated the library. :)
