### ISSUE TITLE
Problem with library

### ISSUE THREAD

**Issue by markowanga** [hanuor/onyx#3]
I tried to use the simplest example (.getTagsfromApi() method) I had got 
`FATAL EXCEPTION: AsyncTask #1
                                                                           Process: pl.marcinwatroba.isithotdog, PID: 1761
                                                                           java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                               at android.os.AsyncTask$3.done(AsyncTask.java:353)
                                                                               at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                               at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                               at java.lang.Thread.run(Thread.java:764)
                                                                            Caused by: com.hanuor.onyx.exceptionhandler.ClarifaiThrottledException: TOO MANY REQUESTS
                                                                               at com.hanuor.onyx.helper.ResponseUtil.throwExceptionForErrorResponse(ResponseUtil.java:52)
                                                                               at com.hanuor.onyx.helper.ClarifaiRequester.executeOnce(ClarifaiRequester.java:91)
                                                                               at com.hanuor.onyx.helper.ClarifaiRequester.execute(ClarifaiRequester.java:40)
                                                                               at com.hanuor.onyx.helper.ClarifaiClient.recognize(ClarifaiClient.java:87)
                                                                               at com.hanuor.onyx.hub.Tags$1.doInBackground(Tags.java:70)
                                                                               at com.hanuor.onyx.hub.Tags$1.doInBackground(Tags.java:65)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                               at java.lang.Thread.run(Thread.java:764) ` 

Are there any issues?

**Comment by hanuor** [comment]
Let me check. Will get back to you as soon as possible.

**Comment by sparxapps** [comment]
Facing the same issue

**Comment by hanuor** [comment]
Issue is occurring because the service provider for this library (Clarifai) have changed there api to a newer version. 
It would take some time for me to migrate the code and hopefully I'll push out a stable update with more features!
Until then, I'm keeping this thread/issue opened.
